version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    ports:
      - "3333:3333"
      - "5555:5555"    # sua API
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mysql
    networks:
      - devnet

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
